name: ci

env:
    CMAKE_BUILD_PARALLEL_LEVEL: 3
    CTEST_PARALLEL_LEVEL: 3
    CMAKE_BUILD_TYPE: Release

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci.yml"

jobs:

  linux:
    runs-on: ubuntu-latest
    env:
      CC: clang
      CXX: clang++

    steps:
    - uses: actions/checkout@v2

    - run: cmake -B build
    - run: cmake --build build
    - run: ctest --test-dir build --preset default


  macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - run: cmake -Bbuild
    - run: cmake --build build
    - run: ctest --test-dir build --preset default

  windows-msvc:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - run: cmake -Bbuild
    - run: cmake --build build
    - run: ctest --test-dir build -C Debug

  windows-gcc:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-gcc

    - uses: actions/checkout@v2

    - run: cmake -Bbuild -G Ninja
    - run: cmake --build build
    - run: ctest --test-dir build
