name: cmake

on:
  push:
    paths:
      - "**.cpp"
      - "**.ixx"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/cmake.yml"

jobs:

  core:

    strategy:
      matrix:
        conf: [ {os: ubuntu-22.04, cpp: g++-12, c: gcc-12},
                {os: macos-latest, cpp: clang++, c: clang} ]

    runs-on: ${{ matrix.conf.os }}

    env:
      CXX: ${{ matrix.conf.cpp }}
      CC: ${{ matrix.conf.c }}

    steps:
    - uses: actions/checkout@v3

    - run: cmake --workflow --preset default


  windows-msvc:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - run: cmake -Bbuild
    - run: cmake --build build --parallel
    - run: ctest --test-dir build -C Debug -V
