name: cmake

on:
  push:
    branches: main
    paths:
      - "**.md"
      - "LICENSE"
      - "**.build"
      - "**.json"
      - "**.f90"
      - "**.F90"
      - "**.lua"
      - ".github/workflows/xmake.yml"

jobs:

  linux:
    runs-on: ubuntu-latest
    env:
      CC: clang
      CXX: clang++

    steps:
    - uses: actions/checkout@v3

    - run: cmake -B build
    - run: cmake --build build --parallel
    - run: ctest --test-dir build --preset default


  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        compiler: [ {cpp: g++-11, c: gcc-11}, {cpp: clang++, c: clang} ]

    steps:
    - uses: actions/checkout@v3

    - run: cmake -Bbuild
      env:
        CXX: ${{ matrix.compiler.cpp }}
        CC: ${{ matrix.compiler.c }}

    - run: cmake --build build --parallel
    - run: ctest --test-dir build --preset default


  windows-msvc:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - run: cmake -Bbuild
    - run: cmake --build build --parallel
    - run: ctest --test-dir build -C Debug -V
