name: cmake

on:
  push:
    paths:
      - "**.cpp"
      - "**.ixx"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/cmake.yml"

env:
  CTEST_NO_TESTS_ACTION: error
  CTEST_PARALLEL_LEVEL: 4


jobs:

  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        v: [9, 10, 11, 12, 13]

    env:
      CXX: g++-${{ matrix.v }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Ninja for C++ modules
      run: sudo apt-get install ninja-build

    - run: cmake --workflow --preset debug

    - run: cmake --workflow --preset release


  mac:
    runs-on: macos-14
    timeout-minutes: 5

    env:
      HOMEBREW_NO_AUTO_CLEANUP: 1
      CXX: ${{ matrix.cxx }}

    strategy:
      matrix:
        cxx: [g++-13, clang++]

    steps:
    - uses: actions/checkout@v4

    - name: Install Ninja for C++ modules
      run: brew install ninja

    - run: sudo xcode-select --switch /Applications/Xcode_15.1.app
    # https://docs.brew.sh/Xcode
    # https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/os/mac/xcode.rb#L20

    - run: cmake --workflow --preset debug

    - run: cmake --workflow --preset release



  windows-msvc:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - run: cmake --workflow --preset msvc
