name: cmake

on:
  push:
    paths:
      - "**.cpp"
      - "**.ixx"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/cmake.yml"

env:
  CTEST_NO_TESTS_ACTION: error
  CTEST_PARALLEL_LEVEL: 0
  CMAKE_BUILD_PARALLEL_LEVEL: 4
  HOMEBREW_NO_AUTO_UPDATE: 1


jobs:

  gcc-new:
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    strategy:
      matrix:
        v: [12, 13, 14]

    env:
      CXX: g++-${{ matrix.v }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Ninja
      run: sudo apt-get install ninja-build

    - run: cmake --workflow --preset debug

    - run: cmake --workflow --preset release


  gcc-old:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    strategy:
      matrix:
        v: [9, 10, 11]

    env:
      CXX: g++-${{ matrix.v }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Ninja
      run: sudo apt-get install ninja-build

    - run: cmake --workflow --preset debug

    - run: cmake --workflow --preset release


  mac:
    runs-on: macos-14
    timeout-minutes: 5

    env:
      HOMEBREW_NO_AUTO_CLEANUP: 1
      CXX: ${{ matrix.cxx }}

    strategy:
      matrix:
        cxx: [g++-13, clang++]

    steps:
    - name: Install Ninja
      run: brew install ninja

    - run: sudo xcode-select --switch /Applications/Xcode_15.1.app
    # https://docs.brew.sh/Xcode
    # https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/os/mac/xcode.rb#L20

    - uses: actions/checkout@v4

    - run: cmake --workflow --preset debug

    - run: cmake --workflow --preset release



  windows-msvc:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - run: cmake --workflow --preset msvc
