name: cmake

on:
  push:
    paths:
      - "**.cpp"
      - "**.ixx"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/cmake.yml"

jobs:

  core:

    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest]
        compiler: [ {cpp: g++-11, c: gcc-11}, {cpp: clang++, c: clang} ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - run: cmake --workflow --preset default
      env:
        CXX: ${{ matrix.compiler.cpp }}
        CC: ${{ matrix.compiler.c }}


  windows-msvc:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - run: cmake -Bbuild
    - run: cmake --build build --parallel
    - run: ctest --test-dir build -C Debug -V
